-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 19:46:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bairronline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bairronline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bairronline` DEFAULT CHARACTER SET utf8 ;
USE `bairronline` ;

-- -----------------------------------------------------
-- Table `bairronline`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`usuario` (
  `usu_cod` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(45) NOT NULL,
  `usu_email` VARCHAR(45) NOT NULL,
  `usu_senha` VARCHAR(65) NOT NULL,
  `usu_tel` VARCHAR(20) NOT NULL,
  `usu_img` VARCHAR(60) NOT NULL,
  `usu_cep` VARCHAR(45) NOT NULL,
  `usu_data` DATE NOT NULL,
  `usu_tipo` ENUM('denunciante', 'instituicao', 'administrador') NOT NULL,
  PRIMARY KEY (`usu_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`denuncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`denuncias` (
  `den_cod` INT NOT NULL AUTO_INCREMENT,
  `den_nome` VARCHAR(45) NOT NULL,
  `den_prazo` DATE NOT NULL,
  `den_desc` MEDIUMTEXT NOT NULL,
  `den_data` DATE NOT NULL,
  `den_img` VARCHAR(60) NOT NULL,
  `den_bairro` VARCHAR(30) NOT NULL,
  `den_problema` VARCHAR(45) NOT NULL,
  `den_like` INT NOT NULL,
  `den_like_users` JSON NULL,
  `usuario_usu_cod` INT NOT NULL,
  PRIMARY KEY (`den_cod`),
  INDEX `fk_denuncias_usuario1_idx` (`usuario_usu_cod` ASC),
  CONSTRAINT `fk_denuncias_usuario1`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`comentarios` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `com_conteudo` MEDIUMTEXT NOT NULL,
  `com_data` DATE NOT NULL,
  `com_editado_por` VARCHAR(45) NOT NULL,
  `com_editado_em` DATE NOT NULL,
  `denuncias_den_cod` INT NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  PRIMARY KEY (`com_id`),
  INDEX `fk_comentarios_denuncias1_idx` (`denuncias_den_cod` ASC),
  INDEX `fk_comentarios_usuario1_idx` (`usuario_usu_cod` ASC),
  CONSTRAINT `fk_comentarios_denuncias1`
    FOREIGN KEY (`denuncias_den_cod`)
    REFERENCES `bairronline`.`denuncias` (`den_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`acompanhamento` (
  `aco_num` INT NOT NULL AUTO_INCREMENT,
  `aco_data` DATE NOT NULL,
  `aco_progresso` DATE NOT NULL,
  `aco_mensagem` MEDIUMTEXT NOT NULL,
  `aco_subtarefa` VARCHAR(20) NOT NULL,
  `denuncias_den_cod` INT NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  PRIMARY KEY (`aco_num`),
  INDEX `fk_acompanhamento_denuncias1_idx` (`denuncias_den_cod` ASC),
  INDEX `fk_acompanhamento_usuario1_idx` (`usuario_usu_cod` ASC),
  CONSTRAINT `fk_acompanhamento_denuncias1`
    FOREIGN KEY (`denuncias_den_cod`)
    REFERENCES `bairronline`.`denuncias` (`den_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acompanhamento_usuario1`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`denuncias_excluidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`denuncias_excluidas` (
  `den_cod` INT NOT NULL AUTO_INCREMENT,
  `den_nome` VARCHAR(45) NOT NULL,
  `den_prazo` DATE NOT NULL,
  `den_desc` MEDIUMTEXT NOT NULL,
  `den_data` DATE NOT NULL,
  `den_img` VARCHAR(60) NOT NULL,
  `den_bairro` VARCHAR(30) NOT NULL,
  `den_problema` VARCHAR(45) NOT NULL,
  `den_like` INT NOT NULL,
  `den_motivo_exclusao` VARCHAR(30) NOT NULL,
  `den_data_exclusao` DATE NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  PRIMARY KEY (`den_cod`),
  INDEX `fk_denuncias_usuario1_idx` (`usuario_usu_cod` ASC),
  CONSTRAINT `fk_denuncias_usuario10`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`notificacao` (
  `not_cod` INT NOT NULL AUTO_INCREMENT,
  `not_titulo` VARCHAR(25) NOT NULL,
  `not_mensagem` MEDIUMTEXT NOT NULL,
  `not_data` DATE NOT NULL,
  `not_lida` TINYINT NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  `denuncias_den_cod` INT NOT NULL,
  INDEX `fk_denuncias_usuario1_idx` (`usuario_usu_cod` ASC),
  PRIMARY KEY (`not_cod`),
  INDEX `fk_notificacao_denuncias1_idx` (`denuncias_den_cod` ASC),
  CONSTRAINT `fk_denuncias_usuario11`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_denuncias1`
    FOREIGN KEY (`denuncias_den_cod`)
    REFERENCES `bairronline`.`denuncias` (`den_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`subtarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`subtarefa` (
  `sub_cod` INT NOT NULL AUTO_INCREMENT,
  `sub_data_inicio` DATE NOT NULL,
  `sub_data_conclusao` DATE NOT NULL,
  `sub_texto` VARCHAR(45) NOT NULL,
  `sub_prioridade` ENUM('alta', 'media', 'baixa') NOT NULL,
  `sub_estado` ENUM('andamento', 'concluida') NOT NULL,
  `acompanhamento_aco_num` INT NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  INDEX `fk_subtarefa_acompanhamento1_idx` (`acompanhamento_aco_num` ASC),
  INDEX `fk_subtarefa_usuario1_idx` (`usuario_usu_cod` ASC),
  PRIMARY KEY (`sub_cod`),
  CONSTRAINT `fk_subtarefa_acompanhamento1`
    FOREIGN KEY (`acompanhamento_aco_num`)
    REFERENCES `bairronline`.`acompanhamento` (`aco_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subtarefa_usuario1`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bairronline`.`reportar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bairronline`.`reportar` (
  `rep_cod` INT NOT NULL AUTO_INCREMENT,
  `rep_motivo` MEDIUMTEXT NOT NULL,
  `rep_data` DATE NOT NULL,
  `rep_acao_tomada` VARCHAR(45) NOT NULL,
  `rep_status` ENUM('pendente', 'analise', 'resolvido') NOT NULL,
  `denuncias_den_cod` INT NOT NULL,
  `usuario_usu_cod` INT NOT NULL,
  PRIMARY KEY (`rep_cod`),
  INDEX `fk_comentarios_denuncias1_idx` (`denuncias_den_cod` ASC),
  INDEX `fk_comentarios_usuario1_idx` (`usuario_usu_cod` ASC),
  CONSTRAINT `fk_comentarios_denuncias10`
    FOREIGN KEY (`denuncias_den_cod`)
    REFERENCES `bairronline`.`denuncias` (`den_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuario10`
    FOREIGN KEY (`usuario_usu_cod`)
    REFERENCES `bairronline`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
